version: '3.3'
services:
  # deno:
  #   image: 'mdillon/postgis:10-alpine'
  #   container_name: deno.db
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=Click123
  #     - POSTGRES_DB=deno
  deno-pgvector:
    image: pgvector/pgvector:pg15 # or pgvector:pg16, depending on your version
    container_name: deno-pgvector.db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Click123
      - POSTGRES_DB=deno
volumes:
  pgdata:
